# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/code-file/FPGA/HLS/hls_helloworld/HLS_HelloWorld/HLS_HelloWorld.srcs/sources_1/ip/flash_led_0/flash_led_0.xci
# IP: The module: 'flash_led_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code-file/FPGA/HLS/hls_helloworld/HLS_HelloWorld/HLS_HelloWorld.srcs/sources_1/ip/flash_led_0/constraints/flash_led_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'flash_led_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/code-file/FPGA/HLS/hls_helloworld/HLS_HelloWorld/HLS_HelloWorld.srcs/sources_1/ip/flash_led_0/flash_led_0.xci
# IP: The module: 'flash_led_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code-file/FPGA/HLS/hls_helloworld/HLS_HelloWorld/HLS_HelloWorld.srcs/sources_1/ip/flash_led_0/constraints/flash_led_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'flash_led_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
