set_property SRC_FILE_INFO {cfile:D:/code-file/FPGA/HLS/hls_helloworld/HLS_HelloWorld/HLS_HelloWorld.srcs/top_pin.xdc rfile:../../../HLS_HelloWorld.srcs/top_pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports {led_o}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports {rst_n}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports {clk}]
